"""initial schema

Revision ID: a00751e3c036
Revises: 
Create Date: 2026-08-29 14:15:25.970116

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a00751e3c036'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('items_ingested', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_ingestion_runs_org_id'), 'ingestion_runs', ['org_id'], unique=False)
    op.create_table('integration_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('creds_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'type')
    )
    op.create_index(op.f('ix_integration_connections_org_id'), 'integration_connections', ['org_id'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'user_id')
    )
    op.create_index(op.f('ix_memberships_org_id'), 'memberships', ['org_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('report_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('catalog_version', sa.String(length=32), nullable=False),
    sa.Column('manifest_hash', sa.String(length=64), nullable=False),
    sa.Column('report_json', sa.JSON(), nullable=False),
    sa.Column('framework_scope', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_snapshots_org_id'), 'report_snapshots', ['org_id'], unique=False)
    op.create_table('evidence_artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('evidence_type', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('manifest_hash', sa.String(length=64), nullable=True),
    sa.Column('collected_at', sa.Date(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('ingestion_run_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_artifacts_content_hash'), 'evidence_artifacts', ['content_hash'], unique=False)
    op.create_index(op.f('ix_evidence_artifacts_org_id'), 'evidence_artifacts', ['org_id'], unique=False)
    op.create_table('share_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['report_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    op.create_index(op.f('ix_share_links_snapshot_id'), 'share_links', ['snapshot_id'], unique=False)
    op.create_table('control_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artifact_id', sa.UUID(), nullable=False),
    sa.Column('control_id', sa.String(length=64), nullable=False),
    sa.Column('obligation_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('catalog_version', sa.String(length=32), nullable=False),
    sa.Column('suggested_by_ml', sa.Boolean(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('mapped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['evidence_artifacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_control_mappings_artifact_control', 'control_mappings', ['artifact_id', 'control_id'], unique=False)
    op.create_index(op.f('ix_control_mappings_artifact_id'), 'control_mappings', ['artifact_id'], unique=False)
    op.create_index(op.f('ix_control_mappings_control_id'), 'control_mappings', ['control_id'], unique=False)
    op.create_index(op.f('ix_control_mappings_obligation_id'), 'control_mappings', ['obligation_id'], unique=False)
    op.create_table('ml_proposals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('artifact_id', sa.UUID(), nullable=True),
    sa.Column('control_id', sa.String(length=64), nullable=True),
    sa.Column('proposal_json', sa.JSON(), nullable=False),
    sa.Column('parent_evidence_hash', sa.String(length=64), nullable=True),
    sa.Column('prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('prev_proposal_hash', sa.String(length=64), nullable=True),
    sa.Column('this_proposal_hash', sa.String(length=64), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['evidence_artifacts.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_proposals_artifact_id'), 'ml_proposals', ['artifact_id'], unique=False)
    op.create_index(op.f('ix_ml_proposals_control_id'), 'ml_proposals', ['control_id'], unique=False)
    op.create_index(op.f('ix_ml_proposals_org_id'), 'ml_proposals', ['org_id'], unique=False)
    op.create_index(op.f('ix_ml_proposals_parent_evidence_hash'), 'ml_proposals', ['parent_evidence_hash'], unique=False)
    op.create_index(op.f('ix_ml_proposals_this_proposal_hash'), 'ml_proposals', ['this_proposal_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ml_proposals_this_proposal_hash'), table_name='ml_proposals')
    op.drop_index(op.f('ix_ml_proposals_parent_evidence_hash'), table_name='ml_proposals')
    op.drop_index(op.f('ix_ml_proposals_org_id'), table_name='ml_proposals')
    op.drop_index(op.f('ix_ml_proposals_control_id'), table_name='ml_proposals')
    op.drop_index(op.f('ix_ml_proposals_artifact_id'), table_name='ml_proposals')
    op.drop_table('ml_proposals')
    op.drop_index(op.f('ix_control_mappings_obligation_id'), table_name='control_mappings')
    op.drop_index(op.f('ix_control_mappings_control_id'), table_name='control_mappings')
    op.drop_index(op.f('ix_control_mappings_artifact_id'), table_name='control_mappings')
    op.drop_index('ix_control_mappings_artifact_control', table_name='control_mappings')
    op.drop_table('control_mappings')
    op.drop_index(op.f('ix_share_links_snapshot_id'), table_name='share_links')
    op.drop_table('share_links')
    op.drop_index(op.f('ix_evidence_artifacts_org_id'), table_name='evidence_artifacts')
    op.drop_index(op.f('ix_evidence_artifacts_content_hash'), table_name='evidence_artifacts')
    op.drop_table('evidence_artifacts')
    op.drop_index(op.f('ix_report_snapshots_org_id'), table_name='report_snapshots')
    op.drop_table('report_snapshots')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_org_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_integration_connections_org_id'), table_name='integration_connections')
    op.drop_table('integration_connections')
    op.drop_index(op.f('ix_ingestion_runs_org_id'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
